dataset: GEOM  # NOTE: must be one of (`QM9`, `GEOM`)
model_type: Unconditional  # NOTE: must be one of (`Unconditional`, `Conditional`)
sampling_index: 0  # NOTE: must be one of (`0`, `1`, `2`, `3`, `4`)
method_1: gcdm  # NOTE: must be one of (`gcdm`, `geoldm`)
method_2: geoldm  # NOTE: must be one of (`gcdm`, `geoldm`)
property: ''  # NOTE: if `model_type` is `Conditional`, must be one of (`_alpha`, `_gap`, `_homo`, `_lumo`, `_mu`, `_Cv`)
bust_column_name: energy_ratio  # column name in the bust results file
method_1_bust_results_filepath: ${oc.env:PROJECT_ROOT}/output/${dataset}/${model_type}_analysis/${method_1}${property}_molecule_bust_results_${sampling_index}.csv # filepath to which bust results were saved
method_2_bust_results_filepath: ${oc.env:PROJECT_ROOT}/output/${dataset}/${model_type}_analysis/${method_2}${property}_molecule_bust_results_${sampling_index}.csv # filepath to which bust results were saved
bust_analysis_plot_filepath: ${oc.env:PROJECT_ROOT}/output/${dataset}/${model_type}_analysis/${method_1}_${method_2}${property}_bust_analysis_${sampling_index}.png # filepath to which bust analysis plot will be saved
verbose: true  # whether to print additional information
