dataset: QM9
data_dir: ${paths.data_dir}EDM
smiles_filepath: ${.data_dir}/QM9/QM9_smiles.pickle
num_atom_types: 5
num_x_dims: 3
remove_h: false
create_pyg_graphs: true
num_train: -1
num_valid: -1
num_test: -1
subtract_thermo: true
filter_n_atoms: null
include_charges: true
filter_molecule_size: null
sequential: false
device: cpu
force_download: false
num_radials: 1
batch_size: 64
num_workers: 4
shuffle: true
drop_last: true
pin_memory: false
