dataset: GEOM
data_dir: ${paths.data_dir}EDM
smiles_filepath: ${.data_dir}/GEOM/GEOM_drugs_smiles.txt
num_atom_types: 16
num_x_dims: 3
remove_h: false
create_pyg_graphs: true
num_train: -1
num_valid: -1
num_test: -1
subtract_thermo: true
filter_n_atoms: null
include_charges: false
filter_molecule_size: null
sequential: false
device: cpu
force_download: false
num_radials: 1
batch_size: 64
num_workers: 4
shuffle: true
drop_last: true
pin_memory: false
