apiVersion: v1
kind: Pod
metadata:
  name: $USER-data-transfer-pod-pvc # REPLACE $USER with your Nautilus username
spec:
  containers:
    - name: $USER-data-transfer-pod-pvc # REPLACE $USER with your Nautilus username
      image: ubuntu:20.04
      command: ["sh", "-c", "echo 'I am a new pod for data transfers to one of my PVCs' && sleep infinity"]
      resources:
        limits:
          memory: 12Gi
          cpu: 2
        requests:
          memory: 10Gi
          cpu: 2
      volumeMounts:
        - mountPath: /data
          name: $USER-bio-diffusion-pvc # REPLACE $USER with your Nautilus username
  volumes:
    - name: $USER-bio-diffusion-pvc # REPLACE $USER with your Nautilus username
      persistentVolumeClaim:
        claimName: $USER-bio-diffusion-pvc # REPLACE $USER with your Nautilus username
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-central