# https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/common/callbacks/ema.py

# Maintains an exponential moving average (EMA) of model weights.
# Look at the above link for more detailed information regarding the original implementation.
ema:
  _target_: src.utils.EMA
  decay: 0.9999
  apply_ema_every_n_steps: 1
  start_step: 0
  save_ema_weights_in_callback_state: true
  evaluate_ema_weights_instead: true
