# @package _global_

defaults:
  - _self_
  - datamodule: edm_qm9.yaml # choose datamodule with `val_dataloader()` and `test_dataloader()` for evaluation
  - model: qm9_mol_gen_ddpm.yaml
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# inference (i.e., sampling) and evaluation arguments
generator_model_filepath: ???
classifier_model_dir: ""
property: "alpha"
iterations: 100
batch_size: 100
debug_break: false
sweep_property_values: false
num_sweeps: 10
output_dir: ""